# Stage 1: Build the application
FROM node:14 AS builder

WORKDIR /app

COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

RUN npm run build

# Stage 2: Final image
FROM node:14-alpine

WORKDIR /app

# Copy only necessary files from the previous stage
COPY --from=builder /app .

EXPOSE 3900

# Set environment variables
ENV MONGODB_USERNAME=root
ENV MONGODB_PASSWORD=secret

# Run the application
CMD ["npm", "start"]